name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install texlive
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra
      
      - name: Compile resume
        run: pdflatex "\newcommand{\generated}{by a \textcolor{blue}{\href{https://github.com/germandrummer92/resume/actions/runs/${{ github.run_id  }}}{github action}}}\input{main.tex}"
 

      - uses: actions/upload-artifact@v4
        with:
          name: resume
          path: main.pdf
